services:
  flask:
    build:
      context: flask
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/flaskdb
    depends_on:
      - database
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data    

volumes:
  postgres_data:
